# Generated by Django 2.0.2 on 2018-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0003_auto_20180712_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='colour',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='result',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
