# Generated by Django 2.0.2 on 2018-07-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose', '0004_auto_20180716_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
